apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: app-producao
type: Opaque
data:
  # Lembre-se que os valores são em base64.
  # echo -n 'admin' | base64  => YWRtaW4=
  # echo -n 'SuaSenhaDoDB' | base64
  DB_USER: YWRtaW4=
  DB_PASSWORD: U2VhbHNEQiMyMDI1JlByb2Q= # Senha 'SealsDB#2025&Prod' em base64